In [0]:
import numpy as np

docs = ["너무 재밌네요","최고예요","참 잘 만든 영화예요","추천하고 싶은 영화입니다","한번 더 보고싶네요","글쎄요","별로예요","생각보다 지루하네요","연기가 어색해요","재미없어요"]

y_label = np.array([1,1,1,1,1,0,0,0,0,0])

In [3]:
from tensorflow.keras.preprocessing.text import Tokenizer

token = Tokenizer()
token.fit_on_texts(docs)
print(token.word_index)

{'너무': 1, '재밌네요': 2, '최고예요': 3, '참': 4, '잘': 5, '만든': 6, '영화예요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한번': 11, '더': 12, '보고싶네요': 13, '글쎄요': 14, '별로예요': 15, '생각보다': 16, '지루하네요': 17, '연기가': 18, '어색해요': 19, '재미없어요': 20}


In [4]:
x = token.texts_to_sequences(docs)
print(x)

[[1, 2], [3], [4, 5, 6, 7], [8, 9, 10], [11, 12, 13], [14], [15], [16, 17], [18, 19], [20]]


In [5]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

padded_x = pad_sequences(x, max([len(i) for i in x]))
print(padded_x)

[[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [ 0 11 12 13]
 [ 0  0  0 14]
 [ 0  0  0 15]
 [ 0  0 16 17]
 [ 0  0 18 19]
 [ 0  0  0 20]]


In [8]:
from keras.layers import Embedding, Flatten, Dense
from keras.models import Sequential

word_size = len(token.word_index) + 1

model = Sequential()
model.add(Embedding(word_size, 8, input_length = 4))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(padded_x, y_label, epochs = 20)
print("\n Accuracy: %.4f" %(model.evaluate(padded_x, y_label)[1]))

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/indexed_slices.py:434: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "


Epoch 1/20
10/10 [==============================] - 0s 36ms/step - loss: 0.6922 - accuracy: 0.5000
Epoch 2/20
10/10 [==============================] - 0s 452us/step - loss: 0.6906 - accuracy: 0.5000
Epoch 3/20
10/10 [==============================] - 0s 310us/step - loss: 0.6887 - accuracy: 0.5000
Epoch 4/20
10/10 [==============================] - 0s 133us/step - loss: 0.6867 - accuracy: 0.6000
Epoch 5/20
10/10 [==============================] - 0s 398us/step - loss: 0.6847 - accuracy: 0.6000
Epoch 6/20
10/10 [==============================] - 0s 131us/step - loss: 0.6825 - accuracy: 0.6000
Epoch 7/20
10/10 [==============================] - 0s 153us/step - loss: 0.6804 - accuracy: 0.6000
Epoch 8/20
10/10 [==============================] - 0s 173us/step - loss: 0.6783 - accuracy: 0.6000
Epoch 9/20
10/10 [==============================] - 0s 177us/step - loss: 0.6762 - accuracy: 0.6000
Epoch 10/20
10/10 [==============================] - 0s 199us/step - loss: 0.6740 - accuracy: 0.6000
